// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PartsCom.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class FixProductSubCategoryForeignKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_product_sub_categories_product_categories_id",
                table: "ProductSubCategories");

            migrationBuilder.AddColumn<Guid>(
                name: "product_category_id",
                table: "ProductSubCategories",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_product_sub_categories_product_category_id",
                table: "ProductSubCategories",
                column: "product_category_id");

            migrationBuilder.AddForeignKey(
                name: "fk_product_sub_categories_product_categories_product_category_id",
                table: "ProductSubCategories",
                column: "product_category_id",
                principalTable: "ProductCategories",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_product_sub_categories_product_categories_product_category_id",
                table: "ProductSubCategories");

            migrationBuilder.DropIndex(
                name: "ix_product_sub_categories_product_category_id",
                table: "ProductSubCategories");

            migrationBuilder.DropColumn(
                name: "product_category_id",
                table: "ProductSubCategories");

            migrationBuilder.AddForeignKey(
                name: "fk_product_sub_categories_product_categories_id",
                table: "ProductSubCategories",
                column: "id",
                principalTable: "ProductCategories",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
