#pragma checksum "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e306360e715dae940d1d356c9fdeb48a2b4ddcf2"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCoreGeneratedDocument.home_marek_inzynieriaA_PartsCom_PartsCom_Ui_Views_Home_Index), @"mvc.1.0.view", @"/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml")]
namespace AspNetCoreGeneratedDocument;

#line default
using global::System;
using global::System.Collections.Generic;
using global::System.Linq;
using global::System.Threading.Tasks;
using global::Microsoft.AspNetCore.Mvc;
using global::Microsoft.AspNetCore.Mvc.Rendering;
using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#line default
#line hidden
[global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha1", @"e306360e715dae940d1d356c9fdeb48a2b4ddcf2", @"/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml")]
[global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml")]
[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
#nullable restore
internal sealed class home_marek_inzynieriaA_PartsCom_PartsCom_Ui_Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
#nullable disable
{
#pragma warning disable 1998
    public async override global::System.Threading.Tasks.Task ExecuteAsync()
    {
#nullable restore
#line (1,3)-(3,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"

        ViewData["Title"] = "Home Page";

#line default
#line hidden
#nullable disable

        WriteLiteral(@"
<section class=""container mt-4"">
  <div class=""row g-4"">
    <div class=""col-lg-8"">
      <div class=""p-5 bg-light rounded shadow-sm h-100 d-flex align-items-center justify-content-between"">
        <div>
          <h6 class=""text-primary"">[Super slogan]</h6>
          <h2 class=""fw-bold"">[Produkt]</h2>
          <p>[opis]</p>
          <a href=""#"" class=""btn btn-warning"">[Przycisk Kup]</a>
        </div>
        <img src=""https://via.placeholder.com/200x200"" class=""img-fluid"" alt=""Placeholder"" />
      </div>
    </div>

    <div class=""col-lg-4 d-flex flex-column gap-4"">
      <div class=""p-4 bg-light rounded shadow-sm d-flex justify-content-between align-items-center"">
        <div>
          <h6 class=""text-warning"">[Wyprzedaże]</h6>
          <h5>[Produkt]</h5>
          <a href=""#"" class=""btn btn-outline-primary btn-sm mt-2"">[Przycisk Kup]</a>
        </div>
        <img src=""https://via.placeholder.com/100x100"" alt=""Placeholder"" />
      </div>
      <div class=""p-4 bg-light rounded shadow-sm d-flex j");
        WriteLiteral(@"ustify-content-between align-items-center"">
        <div>
          <h5>[Produkt]</h5>
          <p class=""text-muted mb-1"">[Cena]</p>
          <a href=""#"" class=""btn btn-outline-primary btn-sm"">[Przycisk Kup]</a>
        </div>
        <img src=""https://via.placeholder.com/100x100"" alt=""Placeholder"" />
      </div>
    </div>
  </div>
</section>

<section class=""container my-5"">
  <div class=""row text-center"">
    <div class=""col-md-3""><strong>[Zalety]</strong><br />[Zalety]</div>
    <div class=""col-md-3""><strong>[Zalety]</strong><br />[Zalety]</div>
    <div class=""col-md-3""><strong>[Zalety]</strong><br />[Zalety]</div>
    <div class=""col-md-3""><strong>[Zalety]</strong><br />[Zalety]</div>
  </div>
</section>

<section class=""container mb-5"">
  <div class=""d-flex justify-content-between align-items-center mb-3"">
    <h4 class=""fw-bold"">[Wyprzedaże]</h4>
    <a href=""#"" class=""text-decoration-none"">[Przeglądaj produkty]→</a>
  </div>

  <div class=""row g-4"">
");
#nullable restore
#line (56,6)-(56,35) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        for (int i = 0; i < 8; i++) {

#line default
#line hidden
#nullable disable

            WriteLiteral(@" <div class=""col-md-3"">
      <div class=""card h-100 shadow-sm"">
        <img src=""https://via.placeholder.com/300x200"" class=""card-img-top"" alt=""[Placeholder]"">
        <div class=""card-body"">
          <span class=""badge bg-warning text-dark mb-2"">HOT</span>
          <h6 class=""card-title"">[Product]</h6>
          <p class=""text-muted mb-2"">[Cena]</p>
          <a href=""#"" class=""btn btn-outline-dark w-100"">[Przycisk Kup]</a>
        </div>
      </div>
  </div>
");
#nullable restore
#line (67,1)-(68,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        }

#line default
#line hidden
#nullable disable

        WriteLiteral(@"  </div>
</section>



<section class=""container mb-5"">
  <div class=""d-flex justify-content-between align-items-center mb-3"">
    <h4 class=""fw-bold"">[Wyprzedaże]</h4>
    <a href=""#"" class=""text-decoration-none"">[Przeglądaj produkty] →</a>
  </div>

  <div class=""row g-4"">
");
#nullable restore
#line (80,6)-(80,35) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        for (int i = 0; i < 8; i++) {

#line default
#line hidden
#nullable disable

            WriteLiteral(@" <div class=""col-md-3"">
      <div class=""card h-100 shadow-sm"">
        <img src=""https://via.placeholder.com/300x200"" class=""card-img-top"" alt=""[Placeholder]"">
        <div class=""card-body"">
          <span class=""badge bg-warning text-dark mb-2"">[Baner]</span>
          <h6 class=""card-title"">[Produkt]</h6>
          <p class=""text-muted mb-2"">[Cena]</p>
          <a href=""#"" class=""btn btn-outline-dark w-100"">[Przycisk Kup]</a>
        </div>
      </div>
  </div>
");
#nullable restore
#line (91,1)-(92,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        }

#line default
#line hidden
#nullable disable

        WriteLiteral(@"  </div>
</section>

<div class=""container my-4"">
  <section class=""container-fluid my-5"">
    <div id=""categoriesCarousel"" class=""carousel slide"" data-bs-ride=""carousel"">
      <div class=""carousel-inner"">

        <div class=""carousel-item active"">
          <div class=""d-flex justify-content-center gap-4 flex-wrap"">
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px");
        WriteLiteral(@"; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
          </div>
        </div>

        <div class=""carousel-item"">
          <div class=""d-flex justify-content-center gap-4 flex-wrap"">
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div cla");
        WriteLiteral(@"ss=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
            <div class=""text-center"">
              <div class=""bg-light p-3 rounded-circle mb-2"" style=""width:80px; height:80px;""></div>
              <small>[Produkt]</small>
            </div>
          </div>
        </div>
      </div>

      <button class=""carousel-control-prev"" type=""button"" data-bs-target=""#categoriesCarousel"" data-bs-slide=""prev"">
        <span class=""carousel-control-prev-icon"" aria-hidden=""true""></span>
        <span class=""");
        WriteLiteral(@"visually-hidden"">Previous</span>
      </button>
      <button class=""carousel-control-next"" type=""button"" data-bs-target=""#categoriesCarousel"" data-bs-slide=""next"">
        <span class=""carousel-control-next-icon"" aria-hidden=""true""></span>
        < span class=""visually-hidden"">Next</span>
      </button>
    </div>
  </section>

  <div class=""d-fex justify-content-between align-items-center my-4"">
    <h4 class=""fw-bold"">[Produkt]</h4>
    <a href=""#"">[Przeglądaj produkty] →</a>
  </div>
  <div class=""row"">
");
#nullable restore
#line (175,6)-(175,34) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        for (int i = 0; i < 8; i++){

#line default
#line hidden
#nullable disable

            WriteLiteral(@" <div class=""col-md-3 mb-4"">
      <div class=""card h-100 shadow-sm"">
        <div class=""bg-light"" style=""height:200px;""></div>
        <div class=""card-body d-flex flex-column"">
          <h6 class=""card-title mb-2"">[Produkt]</h6>
          <p class=""text-muted mb-2"">[Cena]</p>
          <a href=""#"" class=""btn btn-outline-dark mt-auto"">[Przycisk Kup]</a>
        </div>
      </div>
  </div>
");
#nullable restore
#line (185,1)-(186,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        }

#line default
#line hidden
#nullable disable

        WriteLiteral(@"</div>

<div class=""container my-4"">

  <div class=""row my-4"">
    <div class=""col-md-4 mb-3"">
      <div class=""bg-warning p-3 rounded text-dark h-100"">
        <h5 class=""mb-2"">[Tytuł promocji]</h5>
        <p>[Opis promocji]</p>
        <p>[Dodatkowe info]</p>
        <a class=""btn btn-warning"" href=""#"">[Przycisk Kup]</a>
      </div>
    </div>
    <div class=""col-md-4 mb-3"">
      <div class=""bg-light p-3 rounded d-flex align-items-center justify-content-between h-100"">
        <div>
          <h5>[Produkt]</h5>
          <a class=""btn btn-outline-primary mt-2"" href=""#"">[Przycisk Kup]</a>
        </div>
        <img src=""https://via.placeholder.com/100x100"" alt=""[Placeholder]"" />
      </div>
    </div>
    <div class=""col-md-4 mb-3"">
      <div class=""bg-light p-3 rounded d-flex align-items-center justify-content-between h-100"">
        <div>
          <h5>[Produkt]</h5>
          <p>[Opis]</p>
          <a class=""btn btn-primary"" href=""#"">[Przycisk Kup]</a>
        </div>
        <img src=""https://via.");
        WriteLiteral("placeholder.com/100x100\" alt=\"[Placeholder]\" />\n      </div>\n    </div>\n  </div>\n\n  <h3 class=\"mb-3\">[Kategoria]</h3>\n  <div class=\"row mb-4\">\n");
#nullable restore
#line (222,6)-(222,35) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        for (int i = 0; i < 8; i++) {

#line default
#line hidden
#nullable disable

            WriteLiteral(@" <div class=""col-md-3 mb-4"">
      <div class=""card h-100 shadow-sm"">
        <div class=""bg-light"" style=""height:150px;""></div>
        <div class=""card-body d-flex flex-column"">
          <h6 class=""card-title mb-2"">[Produkt]</h6>
          <p class=""text-muted mb-2"">[Cena]</p>
          <a href=""#"" class=""btn btn-outline-dark mt-auto"">[Przycisk Kup]</a>
          <div class=""mt-2 d-flex gap-2 flex-wrap"">
            <span class=""badge bg-primary"">[Tag]</span>
            <span class=""badge bg-danger"">[Tag]</span>
            <span class=""badge bg-success"">[Tag]</span>
            <span class=""badge bg-warning text-dark"">[Tag]</span>
          </div>
        </div>
      </div>
  </div>
");
#nullable restore
#line (238,1)-(239,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        }

#line default
#line hidden
#nullable disable

        WriteLiteral(@"</div>

<div class=""row mb-4"">
  <div class=""col-md-4 mb-3"">
    <div class=""bg-warning p-3 rounded h-100 d-flex flex-column justify-content-between"">
      <div>
        <h5 class=""mb-2"">[Produkt]</h5>
        <p>[Opis]</p>
      </div>
      <a class=""btn btn-warning mt-2"" href=""#"">[Przycisk Kup]</a>
    </div>
  </div>
  <div class=""col-md-4 mb-3"">
    <div class=""bg-light p-3 rounded h-100 d-flex flex-column justify-content-between"">
      <div>
        <h5>[Produkt]</h5>
      </div>
      <a class=""btn btn-outline-primary"" href=""#"">[Przycisk Kup]</a>
    </div>
  </div>
  <div class=""col-md-4 mb-3"">
    <div class=""bg-light p-3 rounded h-100 d-flex flex-column justify-content-between"">
      <div>
        <h5>[Produkt]</h5>
        <p>[Opis]</p>
      </div>
      <a class=""btn btn-primary"" href=""#"">[Przycisk Kup]</a>
    </div>
  </div>
</div>

<div class=""bg-light p-4 rounded mb-4"">
  <div class=""d-flex justify-content-between align-items-center mb-3"">
    <h4 class=""fw-bold mb-0"">[Produkt]</h4>
    <");
        WriteLiteral(@"a href=""#"">[Promocja]</a>
  </div>
  <div class=""row align-items-center"">
    <div class=""col-md-6 mb-3"">
      <img src=""https://via.placeholder.com/400x250"" class=""img-fluid rounded"" alt=""[Placeholder]"" />
    </div>
    <div class=""col-md-6"">
      <h5>[Cena]</h5>
      <ul class=""list-unstyled"">
        <li>[Specyfikacja]</li>
        <li>[Specyfikacja]</li>
        <li>[Specyfikacja]</li>
      </ul>
      <a href=""#"" class=""btn btn-primary"">[Przycisk Kup]</a>
    </div>
  </div>
</div>

<div class=""row mb-4"">
  <div class=""col-md-12 mb-3"">
    <span class=""badge bg-info text-dark"">[Promocja]</span>
  </div>

");
#nullable restore
#line (296,4)-(298,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        foreach (string title in new[] { "[Promocja 1]", "[Promocja 2]", "[Promocja 3]", "[Promocja 4]" })
        {

#line default
#line hidden
#nullable disable

            WriteLiteral("  <div class=\"col-md-3 mb-3\">\n    <h5>");
            Write(
#nullable restore
#line (299,10)-(299,15) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
                title

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</h5>\n");
#nullable restore
#line (300,6)-(300,35) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
            for (int i = 0; i < 3; i++) {

#line default
#line hidden
#nullable disable

                WriteLiteral(" <div class=\"border p-2 mb-2\">\n      <p>[Produkt]</p>\n      <p class=\"text-muted\">[Cena]</p>\n  </div>\n");
#nullable restore
#line (304,1)-(305,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
            }

#line default
#line hidden
#nullable disable

            WriteLiteral("</div>\n");
#nullable restore
#line (306,1)-(307,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        }

#line default
#line hidden
#nullable disable

        WriteLiteral(@"</div>

</div>
</div>

<section class=""container my-5"">
  <div class=""d-flex justify-content-between align-items-center mb-3"">
    <h4 class=""fw-bold"">[Wiadomości]</h4>
    <a href=""#"" class=""text-decoration-none"">[Przeglądaj Wiadomości] →</a>
  </div>
  <div class=""row g-4"">
");
#nullable restore
#line (318,6)-(318,35) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        for (int i = 0; i < 3; i++) {

#line default
#line hidden
#nullable disable

            WriteLiteral(@" <div class=""col-md-4"">
      <div class=""card h-100 shadow-sm"">
        <img src=""https://via.placeholder.com/400x250"" class=""card-img-top"" alt=""[Wiadomości]"">
        <div class=""card-body"">
          <h5 class=""card-title"">[Tytuł]</h5>
          <p class=""card-text"">[Opis]</p>
          <p class=""text-muted"">[Wstęp]</p>
          <a href=""#"" class=""btn btn-outline-dark w-100"">[Czytaj Dalej]</a>
        </div>
      </div>
  </div>
");
#nullable restore
#line (329,1)-(330,1) "/home/marek/inzynieriaA/PartsCom/PartsCom.Ui/Views/Home/Index.cshtml"
        }

#line default
#line hidden
#nullable disable

        WriteLiteral("  </div>\n</section>\n");
    }
#pragma warning restore 1998
#nullable restore
    [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
    public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
#nullable disable
#nullable restore
    [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
    public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
#nullable disable
#nullable restore
    [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
    public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
#nullable disable
#nullable restore
    [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
    public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
#nullable disable
#nullable restore
    [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
    public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; } = default!;
#nullable disable
}
#pragma warning restore 1591

